# ========================================
# MQTT LISTENER
# ========================================

# ----------- Mode & Defaults ------------
MODE ?= dev
MQTT_ENV_FILE := ./config/mqtt.$(MODE).env

.PHONY: mqtt-listener

mqtt-listener: ## 📥 Run MQTT listener for incoming spectra
	python -m db_gateway.mqtt_listener
