name: Run tests and upload coverage

on:
  push

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: pat-analysis
          auto-activate-base: false
          python-version: "3.12"
          environment-file: environment.yml  # ✅ Creates the Conda environment from your file

      - name: Install additional dependencies
        shell: bash -l {0}
        run: |
          conda activate pat-analysis
          pip install pytest pytest-cov codecov  # ✅ Install missing test dependencies

      - name: Run tests
        shell: bash -l {0}
        run: |
          conda activate pat-analysis
          pytest --cov=src --cov-branch --cov-report=xml

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}  # ✅ Only needed for private repos
          file: ./coverage.xml
